title: Xiaotian Wang's Homepage
page-top-title: Xiaotian Wang
top-section-bg-text: '<span class="top-quote">To cross paths with you at a conference,<span class="someday-line">someday.</span></span>'
home-subtitle: Xiaotian Wang&ensp;|&ensp;王小天
copyright-text: '&copy; Xiaotian Wang 2023-2026. All Rights Reserved.'
